version: "3" 
services:
  client:
    build: ./client
    ports:
      - 3000:80
    environment:
      #- "BROWSER=none"
      - SERVER_HOST=server:8080
    #command: npm run start
    stdin_open: true

  server:
    build: ./server
